### ISSUE TITLE
Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by Levistator** [DontShaveTheYak/groovy-guru#12]
I just downloaded this extension for VSCode and it fails to start. 

My VSCode version: 
```
Version: 1.58.2 (user setup)
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:10:15.214Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041
```

The error that appeared in Output: Log (Window) *sanitized*
```
[2021-07-23 11:41:45.436] [renderer1] [error] Illegal argument: line must be non-negative: Error: Illegal argument: line must be non-negative
	at Object.P [as illegalArgument] (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1232)
	at new b (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:77:15809)
	at new b (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:77:15222)
	at R (c:\Users\User\.vscode\extensions\dontshavetheyak.groovy-guru-0.1.2\build\extension.js:1:177776)
	at C (c:\Users\User\.vscode\extensions\dontshavetheyak.groovy-guru-0.1.2\build\extension.js:1:177849)
	at K (c:\Users\User\.vscode\extensions\dontshavetheyak.groovy-guru-0.1.2\build\extension.js:1:182143)
	at c:\Users\User\.vscode\extensions\dontshavetheyak.groovy-guru-0.1.2\build\extension.js:1:187550
	at Array.map (<anonymous>)
	at Object.asSymbolInformations (c:\Users\User\.vscode\extensions\dontshavetheyak.groovy-guru-0.1.2\build\extension.js:1:187542)
	at c:\Users\User\.vscode\extensions\dontshavetheyak.groovy-guru-0.1.2\build\extension.js:1:113599
[2021-07-23 11:41:46.457] [renderer1] [error] Illegal argument: line must be non-negative: Error: Illegal argument: line must be non-negative
	at Object.P [as illegalArgument] (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1232)
	at new b (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:77:15809)
	at new b (c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:77:15222)
	at R (c:\Users\User\.vscode\extensions\dontshavetheyak.groovy-guru-0.1.2\build\extension.js:1:177776)
	at C (c:\Users\User\.vscode\extensions\dontshavetheyak.groovy-guru-0.1.2\build\extension.js:1:177849)
	at K (c:\Users\User\.vscode\extensions\dontshavetheyak.groovy-guru-0.1.2\build\extension.js:1:182143)
	at c:\Users\User\.vscode\extensions\dontshavetheyak.groovy-guru-0.1.2\build\extension.js:1:187550
	at Array.map (<anonymous>)
	at Object.asSymbolInformations (c:\Users\User\.vscode\extensions\dontshavetheyak.groovy-guru-0.1.2\build\extension.js:1:187542)
	at c:\Users\User\.vscode\extensions\dontshavetheyak.groovy-guru-0.1.2\build\extension.js:1:113599
```

I'm not really sure what else to include. Let me know if you need any other information.

**Comment by shadycuz** [comment]
Are sure the plugin isn't working? Can you try hovering on a variable? 

![image](https://user-images.githubusercontent.com/17090999/126996768-89011db9-5f66-402e-894b-cf712ea2f8f0.png)

I'm pretty sure I have seen that error as well but the plugin was still working. I'm not sure if this is an issue with the client (this plugin) or the language server.

**Comment by Levistator** [comment]
It appears that the plugin is working. My apologies, I expected
intellisense to provide some more feedback than it did from an empty groovy
file.

My apologies for wasting your time with this, but thank you!

**Comment by shadycuz** [comment]
@Levistator Yeah you wont see much with a blank file. It is a bit lacking in features but we do have some plans for it. We would like to move to Groovy3 and with it will come the ability to display GroovyDoc comments for items.

I belive right now it has Typing stuff and autocomplete for functions/methods. If you have third party Classes you want to import and use then this plugin has a configuration option to set the path to a folder of jar files. It's probably something I should document in the readme. 

Still would like to figure out where this error is coming from, I have seen it before.

**Comment by shadycuz** [comment]
I have a better understanding of what line number is causing this issue but not why. I have asked for some additional help [here](https://github.com/microsoft/vscode-languageserver-node/issues/797).

**Comment by shadycuz** [comment]
@Levistator v0.3.0 is out. It has a fix in the language server for this error 🚀
